### create Order with created user id
POST http://localhost:8000/order-service/{{userId}}/orders
Content-Type: application/json

{
  "productId": "CATALOG-0002",
  "productName": "SPN",
  "unitPrice": "2800",
  "quantity": "50"
}

### get order detail by user id
GET http://localhost:8000/order-service/{{userId}}/orders

### get order detail by order id
GET http://localhost:8000/order-service/orders/6048a075-8707-4038-8527-55e160c55254