### user service health check
GET http://localhost:8000/user-service/health_check
Authorization: Bearer Token {{token}}

### user service 의 health check
GET http://localhost:8000/user-service/welcome
Authorization: Bearer Token {{token}}

### get One user by user id
GET http://localhost:8000/user-service/users/{{userId}}
Authorization: Bearer Token {{token}}

### select all user
GET http://localhost:8000/user-service/users
Authorization: Bearer Token {{token}}

### add user
POST http://localhost:8000/user-service/users
content-Type: application/json

{
  "email": "chobani_mango@test.com",
  "name": "chocho Kim",
  "password": "test12345"
}

### user login
POST http://localhost:8000/user-service/login
content-Type: application/json

{
  "email": "chobani_mango@test.com",
  "password": "test12345"
}

### spring actuator health check
GET http://localhost:8000/user-service/actuator/health

### spring actuator refresh
POST http://localhost:8000/user-service/actuator/refresh

### spring actuator
GET http://localhost:8000/user-service/actuator/beans